version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@form8ion/remark-lint-preset"
    versions:
    - 1.0.12
  - dependency-name: lockfile-lint
    versions:
    - 4.6.0
    - 4.6.1
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
